file-version: 1
vendor: OneLang
name: Core
version: 0.1
languages:
  php:
    native-src-dir: PHP/src
    generator-plugins: [PHP/JsToPhp.yaml]
  csharp:
    native-src-dir: CSharp/src
    generator-plugins: [CSharp/JsToCSharp.yaml]
  python:
    package-dir: onelang_core
    native-src-dir: Python/src
    generator-plugins: [Python/JsToPython.yaml]
  java:
    package-dir: core
    native-src-dir: Java/src
    generator-plugins: [Java/JsToJava.yaml]
