file-version: 1
vendor: OneLang
name: Json
version: 0.1
languages:
  java:
    package-dir: json
    native-src-dir: Java/src
    native-dependencies:
      - { name: com.google.code.gson:gson, version: 2.8.6 }
    generator-plugins: [Java/JsToJava.yaml]
  csharp:
    native-src-dir: CSharp/src
    native-dependencies:
      - { name: Newtonsoft.Json, version: 12.0.3 }
  php:
    native-src-dir: PHP/src
    generator-plugins: [PHP/JsToPhp.yaml]
  python:
    package-dir: onelang_json
    native-src-dir: Python/src
    generator-plugins: [Python/JsToPython.yaml]
