file-version: 1
vendor: OneLang
name: File
version: 0.1
languages:
  php:
    native-src-dir: PHP/src
    generator-plugins: [PHP/OneFile.yaml]
  csharp:
    native-src-dir: CSharp/src
  python:
    package-dir: onelang_file
    native-src-dir: Python/src
  java:
    package-dir: file
    native-src-dir: Java/src
